version: "3.5"
services:
  etc-core-geth.public.dappnode.eth:
    image: "etc-core-geth.public.dappnode.eth:0.1.2"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.12.13
    volumes:
      - "data:/root/.ethereum"
    environment:
      - "EXTRA_OPTS=--http.api eth,net,web3,txpool"
      - SYNCMODE=snap
      - P2P_PORT=30913
    ports:
      - "30913:30913/udp"
      - "30913:30913/tcp"
    restart: unless-stopped
volumes:
  data: {}
